import 'package:ai_partner/logic/services/storage_service.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:ai_partner/models/scan_result_model.dart';
import 'history_state.dart';

class HistoryCubit extends Cubit<HistoryState> {
  final StorageService _storageService;

  HistoryCubit(this._storageService) : super(HistoryInitial());

  Future<void> loadHistory() async {
    emit(HistoryLoading());
    try {
      final scans = await _storageService.getHistory();
      emit(HistoryLoaded(scans));
    } catch (e) {
      emit(HistoryError("Could not load history."));
    }
  }

  /// Modified: Converts VisionResult objects to JSON,
  /// keeping the ID generated by the model.
  Future<void> saveNewScan(List<VisionResult> results) async {
    try {
      // res.toJson() must include the 'id' field
      final resultsJson = results.map((res) => res.toJson()).toList();

      await _storageService.saveScan(resultsJson);

      // Refresh state to update the bookmark icon in the UI immediately
      await loadHistory();
    } catch (e) {
      emit(HistoryError("Failed to save."));
    }
  }

  void toggleFavorite(String id) async {
    if (state is HistoryLoaded) {
      final List<Map<String, dynamic>> currentHistory = List.from(
        (state as HistoryLoaded).savedScans,
      );

      for (var entry in currentHistory) {
        if (entry['id'] == id) {
          final results = entry['results'] as List;
          if (results.isNotEmpty) {
            results[0]['isFavorite'] = !(results[0]['isFavorite'] ?? false);
          }
        }
      }

      await _storageService.saveFullHistory(currentHistory);
      emit(HistoryLoaded(currentHistory));
    }
  }

  void updateLabel(String id, String newLabel) async {
    if (state is HistoryLoaded) {
      await _storageService.updateScanLabel(id, newLabel);
      final updatedHistory = await _storageService.getHistory();
      emit(HistoryLoaded(updatedHistory));
    }
  }

  /// This is now more reliable because it uses the ID
  /// shared between the VisionResult and the Storage.
  Future<void> deleteItem(String id) async {
    try {
      await _storageService.deleteScanById(id);
      await loadHistory();
    } catch (e) {
      emit(HistoryError("Delete failed."));
    }
  }

  Future<void> clearAll() async {
    try {
      await _storageService.deleteAll();
      emit(HistoryLoaded(const []));
    } catch (e) {
      emit(HistoryError("Failed to clear history."));
    }
  }
}
