arb-dir: lib/core/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
# This line creates the file that tells you what is missing in French
untranslated-messages-file: missing_translations.json